insert into country values('Islamic Republic of Afghanistan');
insert into country values('Republic of Albania');
insert into country values('Peoples Republic of Algeria');
insert into country values('Principality of Andorra');
insert into country values('Republic of Angola');
insert into country values('Antigua and Barbuda');
insert into country values('Argentine Republic of Argentina');
insert into country values('Republic of Armenia');
insert into country values('Commonwealth of Australia');
insert into country values('Republic of Austria');
insert into country values('Republic of Azerbaijan');
insert into country values('The Commonwealth of Bahamas');
insert into country values('Kingdom of Bahrain');
insert into country values('Peoples Republic of Bangladesh');
insert into country values('Barbados');
insert into country values('Republic of Belarus');
insert into country values('Kingdom of Belgium');
insert into country values('Belize');
insert into country values('Republic of Benin');
insert into country values('Kingdom of Bhutan');
insert into country values('Plurinational State of Bolivia');
insert into country values('Republic of Bosnia');
insert into country values('Republic of Botswana');
insert into country values('Federative Republic of Brazil');
insert into country values('Nation of Brunei');
insert into country values('Republic of Bulgaria');
insert into country values('Burkina Faso');
insert into country values('Republic of Burundi');
insert into country values('Kingdom of Cambodia');
insert into country values('Republic of Cameroon');
insert into country values('Canada');
insert into country values('Cape Verde');
insert into country values('Republic of Chad');
insert into country values('Republic of Chile');
insert into country values('Peoples Republic of China');
insert into country values('Republic of Colombia');
insert into country values('Union Of Comoros');
insert into country values('Democractic Republic of The Congo');
insert into country values('Costa Rica');
insert into country values('Republic of Croatia');
insert into country values('Republic of Cuba');
insert into country values('Republic of Cyprus');
insert into country values('Czech Republic');
insert into country values('Kingdom of Denmark');
insert into country values('Republic of Djibouti');
insert into country values('Commonwealth of Dominica');
insert into country values('Dominican Republic');
insert into country values('East Timor');
insert into country values('Republic of Ecuador');
insert into country values('Arab Republic of Egypt');
insert into country values('Republic of El Salvador');
insert into country values('Republic of Equatorial New Guinea');
insert into country values('State of Eritrea');
insert into country values('Republic of Estonia');
insert into country values('Kingdom of Eswatini');
insert into country values('Federal Democratic Republic of Ethiopia');
insert into country values('Republic of Fiji');
insert into country values('Republic of Finland');
insert into country values('French Republic of France');
insert into country values('Gabonense Republic of Gabon');
insert into country values('Republic of The Gambia');
insert into country values('Georgia');
insert into country values('Federal Republic of Germany');
insert into country values('Republic of Ghana');
insert into country values('Hellinic Republic Of Greece');
insert into country values('Grenada');
insert into country values('Republic of Guatemala');
insert into country values('Republic Of Guinea');
insert into country values('Republic of Guinea-Bissau');
insert into country values('Co-Operative Republic of Guyana');
insert into country values('Republic of Haiti');
insert into country values('Republic of Honduras');
insert into country values('Hungary');
insert into country values('Iceland');
insert into country values('Repulic of India');
insert into country values('Republic of Indonesia');
insert into country values('Islamic Republic of Iran');
insert into country values('Republic of Iraq');
insert into country values('Ireland');
insert into country values('State Of Israel');
insert into country values('Italian Republic of Italy');
insert into country values('Republic Of Ivory Coast');
insert into country values('Jamaica');
insert into country values('Japan');
insert into country values('Hashemite Kingdom Of Jordan');
insert into country values('Republic Of Kazakhstan');
insert into country values('Republic of Kenya');
insert into country values('Republic Of Kiribati');
insert into country values('North Korea');
insert into country values('South Korea');
insert into country values('State of Kuwait');
insert into country values('Kyrgyz Republic Of Kyrgyzstan');
insert into country values('Peoples Democratic Republic of Laos');
insert into country values('Republic of Latvia');
insert into country values('Lebanese Republic of Lebanon');
insert into country values('Kingdom Of Lesotho');
insert into country values('Republic of Liberia');
insert into country values('State of Libya');
insert into country values('Principality of Liechtenstein');
insert into country values('Republic of Lithuania');
insert into country values('Luxembourg');
insert into country values('Republic of Madagascar');
insert into country values('Republic Of Malawi');
insert into country values('Malaysia');
insert into country values('Republic of Maldives');
insert into country values('Republic of Mali');
insert into country values('Republic of Malta');
insert into country values('Republic Of The Marshall Islands');
insert into country values('Islamic Republic Of Mauritania');
insert into country values('Republic Of Mauritius');
insert into country values('Mexico');
insert into country values('Micronesia');
insert into country values('Moldova');
insert into country values('Monaco');
insert into country values('Mongolia');
insert into country values('Montenegro');
insert into country values('Morocco');
insert into country values('Mozambique');
insert into country values('Myanmar');
insert into country values('Namibia');
insert into country values('Republic of Nauru');
insert into country values('Federal Democratic Republic of Nepal');
insert into country values('Netherlands');
insert into country values('New Zealand');
insert into country values('Republic of Nicaragua');
insert into country values('Republic of Niger');
insert into country values('Federal Republic of Nigeria');
insert into country values('Republic of North Macedonia');
insert into country values('Norway');
insert into country values('Sultanate Oman');
insert into country values('Pakistan');
insert into country values('Republic of Palau');
insert into country values('Palestine');
insert into country values('Panama');
insert into country values('Papua New Guinea');
insert into country values('Paraguay');
insert into country values('Peru');
insert into country values('Philippines');
insert into country values('Poland');
insert into country values('Portugal');
insert into country values('Qatar');
insert into country values('Romania');
insert into country values('Russia');
insert into country values('Rwanda');
insert into country values('Saint Kitts');
insert into country values('Saint Lucia');
insert into country values('Saint Vicent');
insert into country values('Samoa');
insert into country values('San Marino');
insert into country values('Saudi Arabia');
insert into country values('Senegal');
insert into country values('Serbia');
insert into country values('Seychelles
insert into country values('Sierra Leone');
insert into country values('Singapore');
insert into country values('Slovakia');
insert into country values('Slovenia');
insert into country values('Solomon Islands');
insert into country values('Somalia');
insert into country values('South Africa');
insert into country values('South Sudan');
insert into country values('Spain');
insert into country values('Sri');
insert into country values('Sudan');
insert into country values('Suriname');
insert into country values('Sweden');
insert into country values('Syria');
insert into country values('Tajikistan');
insert into country values('Tanzania');
insert into country values('Thailand');
insert into country values('Togo');
insert into country values('Tonga');
insert into country values('Trinidad');
insert into country values('Tunisia');
insert into country values('Turkey');
insert into country values('Turkmenistan');
insert into country values('Tuvalu');
insert into country values('Uganda');
insert into country values('Ukraine');
insert into country values('United');
insert into country values('United');
insert into country values('United');
insert into country values('Uruguay');
insert into country values('Uzbekistan');
insert into country values('Vanuatu');
insert into country values('Vatican');
insert into country values('Venezuela');
insert into country values('Vietnam');
insert into country values('Yemen');
insert into country values('Zambia');
insert into country values('Zimbabwe');
insert into country values('Abkhazia');
insert into country values('Artsakh');
insert into country values('Cook');
insert into country values('Kosovo');
insert into country values('Niue');
insert into country values('Northern');
insert into country values('Sahrawi');
insert into country values('Somaliland');
insert into country values('South');
insert into country values('Taiwan');
insert into country values('Transnistria');
